name: Go

# on:
#   push:
#     branches: [ master ]
#     paths-ignore:
#     - 'db.sql'
#     - 'index.md'

#   pull_request:
#     branches: [ master ]
#   workflow_dispatch:
#     inputs:
#       git-ref:
#         description: Git Ref (Optional)    
#         required: false
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron: '0 */1 * * *'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Prepare
      run: |
        echo 'GITHUB_TOKEN=${{ secrets.ACCESS_TOKEN }}' > .env
        docker run --name itm --env-file=dbenv -p 3307:3306 -v $(pwd):/tracker -d mysql:8.0 --default-authentication-plugin=mysql_native_password
        docker build . -t issue-tracker

    - name: Wait until database okay
      run: |
        mysql -u root -ppassword -h 127.0.0.1 -P 3307 -e "select 1" || true

    - name: Run tracker
      run: docker run --rm --network="host" --env-file dbenv --env-file .env -v $(pwd):/tracker issue-tracker /bin/sh generate.sh

    - name: Run exporter
      run: docker exec itm /bin/sh /tracker/dump.sh

    - name: Commit files
      run: |
        git config --local user.email "noname@gmail.com"
        git config --local user.name "noname"
        git commit -m "Add changes" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: ${{ github.ref }}

    - name: clean up
      run: docker kill itm
